### ISSUE TITLE
HTTP 503

### ISSUE THREAD

**Issue by albertoalmagro** [iandees/xapi-servlet#1]
Hi Ian,

I have been using successfully your OSM Java XAPI implementation, but now I'm getting HTTP 503, Service unavailable.

Just to make you know.
Regards,
Alberto

**Comment by iandees** [comment]
I'm assuming you mean the version running at jxapi.openstreetmap.org? What request are you making?

**Comment by albertoalmagro** [comment]
Yes, I'm using the version running there, I'm developing an application that makes requests like the following:

http://jxapi.openstreetmap.org/xapi/api/0.6/node[amenity=place_of_worship][bbox=-10.114891357422,42.434477539061,-6.5196154785158,43.807768554686]

Edit: Until today this request was always completed successfully

**Comment by iandees** [comment]
I see nothing that would give a 503. That exact query responded for me just
fine.

It may take 6.5 minutes, but you get data back.

**Comment by albertoalmagro** [comment]
I tried it again now and it took 2 minutes, which is the usual amount of time I have to wait to get the data back

Thank you Ian, SOLVED I close the Issue
Regards
Alberto

**Comment by iandees** [comment]
You may consider using a query that fetches all place_of_worship nodes. That will be significantly faster.

**Comment by albertoalmagro** [comment]
Thank you for the suggestion, I will work on it.

2011/3/15 iandees <
reply@reply.github.com>
