### ISSUE TITLE
All relations returned with *[bbox...] query

### ISSUE THREAD

**Issue by pnorman** [iandees/xapi-servlet#33]
The query `/xapi/api/0.6/*[bbox=-122.81777,49.21784,-122.81005,49.22317]` results in returning all relations.

A bit of investigation finds this is the SQL used to get the relations list

``` sql
CREATE TEMPORARY TABLE bbox_relations ON COMMIT DROP AS 
  SELECT r.* 
    FROM relations r INNER JOIN (
      SELECT relation_id FROM (
        SELECT rm.relation_id AS relation_id 
          FROM relation_members rm
            INNER JOIN bbox_nodes n ON rm.member_id = n.id WHERE rm.member_type = 'N'
        UNION SELECT rm.relation_id AS relation_id 
          FROM relation_members rm
            INNER JOIN bbox_ways w ON rm.member_id = w.id WHERE rm.member_type = 'W'
        ) rids 
      GROUP BY relation_id
    ) rids ON r.id = rids.relation_id 
  UNION SELECT * FROM relations WHERE (1=1)
```

The `SELECT * FROM relations WHERE (1=1)` is the problem, as this returns every relation.

**Comment by iandees** [comment]
Yes, jxapi needs work on relation support.

There was a patch from Matt a while ago that made this search work by building the relation's geometry from its ways and nodes. That made the update process way too slow, though (on my SSD it was not able to keep up with minutelies) and the database got quite a bit bigger on the disk.

The other option is to apply geometry parts of the filter to the ways and nodes tables and the tag parts to the relation table. That would probably work faster, but might be trickier to implement correctly.

**Comment by pnorman** [comment]
Well the problem here is it's getting _both_ relations from parents of geometry and relations with all tags.

**Comment by pnorman** [comment]
Do you know how far I'd have to go back to get a version with the return all relations bug?

**Comment by iandees** [comment]
Relations have never worked properly with jxapi or pyxapi. There was never a version without the return all relations bug.

**Comment by pnorman** [comment]
Returning every relation in the database on a *[bbox...] query is a more recent bug than the ongoing incomplete relations support. 

`curl --globoff 'http://open.mapquestapi.com/xapi/api/0.6/*[bbox=-122.81777,49.21784,-122.81005,49.22317]'` gets 5 relations, but the same query run against a host with the latest xapi version returns ~2 million relations.

**Comment by iandees** [comment]
Ah, I see. This rev looks suspicious... https://github.com/iandees/xapi-servlet/commit/5a078027a18e5e1714df7f1361c46edc8bcae5eb
