### ISSUE TITLE
Add xapi:planetDate attribute to root element

### ISSUE THREAD

**Issue by rjw62** [iandees/xapi-servlet#5]
The regular XAPI includes a number of additional attributes in the root <osm> element, which are not included in the jXAPI implementation. One of these is xapi:planetDate, whose value is a numerical time-stamp string of the form YYYYMMDDhhmm, and which indicated the time associated with the OSM data snapshot used obtain the results.

This timestamp is useful for checking how recent the returned data is, and also for debugging problems. Could it be added to the data returned by jXAPI?

**Comment by Nudin** [comment]
I'd also like to have this.
It makes the oldXAPI incompatible with the new JXAPI.

**Comment by jharris847** [comment]
Ditto.

Without this, I have no confidence that the server is sending data that is remotely up-to-date.

**Comment by iandees** [comment]
This has been added at the expense of removing PBF and JSON support for now.

**Comment by iandees** [comment]
Forgot to add that the timestamp is a UNIX timestamp, not a year/month/day formatted text field.

**Comment by jharris847** [comment]
how does adding one xml attribute an expense of removing PBF and JSON support? Forgive me, but maybe java and xml don't mix as easily as they should?

**Comment by iandees** [comment]
Were you using PBF or JSON? I haven't seen anyone actually use it so I
didn't feel like it was worth spending the time to implement the planetDate
in the other output formats.

**Comment by jharris847** [comment]
No, I wasn't using PBF or JSON, but your comment lead me to believe that adding a planetDate was completely incompatible with PBF or JSON.

I am satisfied with the planetDate now appearing in the XML returned from the jxapi.
